// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: error_code.proto

package codes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	// ERROR_NONE 无意义
	ErrorCode_ERROR_NONE ErrorCode = 0
	// ERROR_PARAMS 参数错误
	ErrorCode_ERROR_PARAMS ErrorCode = 400
	// ERROR_FORBIDDEN 没有权限
	ErrorCode_ERROR_FORBIDDEN ErrorCode = 403
	// ERROR_NOT_FOUND 资源不存在
	ErrorCode_ERROR_NOT_FOUND ErrorCode = 404
	// ERROR_CONFLICT 资源冲突
	ErrorCode_ERROR_CONFLICT ErrorCode = 405
	// ERROR_SERVER_ERROR 服务器错误
	ErrorCode_ERROR_SERVER ErrorCode = 500
	// 数据库错误
	ErrorCode_ERROR_DB ErrorCode = 501
	// 网络错误
	ErrorCode_ERROR_NETWORK ErrorCode = 502
	// 未知错误
	ErrorCode_ERROR_UNKNOWN ErrorCode = 1000
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_NONE",
		400:  "ERROR_PARAMS",
		403:  "ERROR_FORBIDDEN",
		404:  "ERROR_NOT_FOUND",
		405:  "ERROR_CONFLICT",
		500:  "ERROR_SERVER",
		501:  "ERROR_DB",
		502:  "ERROR_NETWORK",
		1000: "ERROR_UNKNOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_NONE":      0,
		"ERROR_PARAMS":    400,
		"ERROR_FORBIDDEN": 403,
		"ERROR_NOT_FOUND": 404,
		"ERROR_CONFLICT":  405,
		"ERROR_SERVER":    500,
		"ERROR_DB":        501,
		"ERROR_NETWORK":   502,
		"ERROR_UNKNOWN":   1000,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_error_code_proto_rawDescGZIP(), []int{0}
}

var File_error_code_proto protoreflect.FileDescriptor

var file_error_code_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x69, 0x62, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x2a, 0xb9, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0c, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x53, 0x10, 0x90, 0x03, 0x12, 0x14, 0x0a, 0x0f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x46, 0x4f,
	0x52, 0x42, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x93, 0x03, 0x12, 0x14, 0x0a, 0x0f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x94, 0x03,
	0x12, 0x13, 0x0a, 0x0e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x4c, 0x49,
	0x43, 0x54, 0x10, 0x95, 0x03, 0x12, 0x11, 0x0a, 0x0c, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53,
	0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0xf4, 0x03, 0x12, 0x0d, 0x0a, 0x08, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x44, 0x42, 0x10, 0xf5, 0x03, 0x12, 0x12, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0xf6, 0x03, 0x12, 0x12, 0x0a, 0x0d, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0xe8, 0x07, 0x42,
	0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x74,
	0x6f, 0x70, 0x78, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_code_proto_rawDescOnce sync.Once
	file_error_code_proto_rawDescData = file_error_code_proto_rawDesc
)

func file_error_code_proto_rawDescGZIP() []byte {
	file_error_code_proto_rawDescOnce.Do(func() {
		file_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_code_proto_rawDescData)
	})
	return file_error_code_proto_rawDescData
}

var file_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_code_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: serverlib.codes.ErrorCode
}
var file_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_code_proto_init() }
func file_error_code_proto_init() {
	if File_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_code_proto_goTypes,
		DependencyIndexes: file_error_code_proto_depIdxs,
		EnumInfos:         file_error_code_proto_enumTypes,
	}.Build()
	File_error_code_proto = out.File
	file_error_code_proto_rawDesc = nil
	file_error_code_proto_goTypes = nil
	file_error_code_proto_depIdxs = nil
}
