// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: server_code.proto

package codes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatusCode int32

const (
	// SERVER_STATUS_NONE 无状态
	ServerStatusCode_SERVER_STATUS_NONE ServerStatusCode = 0
	// SERVER_STATUS_HEALTHY 健康
	ServerStatusCode_SERVER_STATUS_HEALTHY ServerStatusCode = 1
	// SERVER_STATUS_PRESSURE 高负载
	ServerStatusCode_SERVER_STATUS_PRESSURE ServerStatusCode = 2
	// SERVER_STATUS_DISABLE 被禁用
	ServerStatusCode_SERVER_STATUS_DISABLE ServerStatusCode = 3
	// SERVER_STATUS_NETWORK_BAD 网络不通
	ServerStatusCode_SERVER_STATUS_NETWORK_BAD ServerStatusCode = 100
	// SERVER_STATUS_LOGIC_BAD 逻辑报错
	ServerStatusCode_SERVER_STATUS_LOGIC_BAD ServerStatusCode = 101
	// SERVER_STATUS_UNKNOWN 未知状态
	ServerStatusCode_SERVER_STATUS_UNKNOWN ServerStatusCode = 1000
)

// Enum value maps for ServerStatusCode.
var (
	ServerStatusCode_name = map[int32]string{
		0:    "SERVER_STATUS_NONE",
		1:    "SERVER_STATUS_HEALTHY",
		2:    "SERVER_STATUS_PRESSURE",
		3:    "SERVER_STATUS_DISABLE",
		100:  "SERVER_STATUS_NETWORK_BAD",
		101:  "SERVER_STATUS_LOGIC_BAD",
		1000: "SERVER_STATUS_UNKNOWN",
	}
	ServerStatusCode_value = map[string]int32{
		"SERVER_STATUS_NONE":        0,
		"SERVER_STATUS_HEALTHY":     1,
		"SERVER_STATUS_PRESSURE":    2,
		"SERVER_STATUS_DISABLE":     3,
		"SERVER_STATUS_NETWORK_BAD": 100,
		"SERVER_STATUS_LOGIC_BAD":   101,
		"SERVER_STATUS_UNKNOWN":     1000,
	}
)

func (x ServerStatusCode) Enum() *ServerStatusCode {
	p := new(ServerStatusCode)
	*p = x
	return p
}

func (x ServerStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_server_code_proto_enumTypes[0].Descriptor()
}

func (ServerStatusCode) Type() protoreflect.EnumType {
	return &file_server_code_proto_enumTypes[0]
}

func (x ServerStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatusCode.Descriptor instead.
func (ServerStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_server_code_proto_rawDescGZIP(), []int{0}
}

var File_server_code_proto protoreflect.FileDescriptor

var file_server_code_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x69, 0x62, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x2a, 0xd4, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52,
	0x45, 0x53, 0x53, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x42, 0x41, 0x44,
	0x10, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x42, 0x41, 0x44, 0x10, 0x65, 0x12,
	0x1a, 0x0a, 0x15, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0xe8, 0x07, 0x42, 0x22, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x74, 0x6f, 0x70, 0x78, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_code_proto_rawDescOnce sync.Once
	file_server_code_proto_rawDescData = file_server_code_proto_rawDesc
)

func file_server_code_proto_rawDescGZIP() []byte {
	file_server_code_proto_rawDescOnce.Do(func() {
		file_server_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_code_proto_rawDescData)
	})
	return file_server_code_proto_rawDescData
}

var file_server_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_code_proto_goTypes = []interface{}{
	(ServerStatusCode)(0), // 0: serverlib.codes.ServerStatusCode
}
var file_server_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_code_proto_init() }
func file_server_code_proto_init() {
	if File_server_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_code_proto_goTypes,
		DependencyIndexes: file_server_code_proto_depIdxs,
		EnumInfos:         file_server_code_proto_enumTypes,
	}.Build()
	File_server_code_proto = out.File
	file_server_code_proto_rawDesc = nil
	file_server_code_proto_goTypes = nil
	file_server_code_proto_depIdxs = nil
}
